version: "3"

services:
  node:
    build: .
    ports:
      - 53001:3000
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src

  redmine:
    image: redmine
    restart: always
    ports:
      - 53000:3000
    env_file:
      - .env

  db:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    env_file:
      - .env